FROM ubuntu:bionic

ENV DEBIAN_FRONTEND noninteractive

# Install base packages
RUN apt-get update && apt-get install -y \
        software-properties-common \
        locales \
        wget \
        nano \
        libssl1.0-dev libssl1.0 \
    && locale-gen en_US.UTF-8 \
    && export LANG=en_US.UTF-8 \
    && export LC_ALL=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/* \
    && add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get -yq --allow-unauthenticated install \
      php7.2 \
      php7.2-fpm \
      php7.2-curl \
      php7.2-mysql \
      php7.2-sqlite3 \
      php7.2-intl \
      php7.2-msgpack \
      php7.2-memcached \
      php7.2-memcache \
      php7.2-gd \
      php7.2-apc \
      php7.2-ldap \
      php7.2-xml \
      php7.2-mbstring \
      php7.2-zip \
      php7.2-bcmath \
      php7.2-opcache \
      php7.2-readline \
      php7.2-json \
      php-apcu \
      php-apcu-bc \
      libmaxminddb0 \
      libmaxminddb-dev \
      net-tools \
      mmdb-bin \
      curl \
      zip \
      unzip \
      zsh \
      g++ \
      gcc \
      make \
      libxml2 \
      supervisor \
    && rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - \
    && echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list \
    && apt-get update && apt-get install filebeat

COPY config/filebeat.yml /etc/filebeat/filebeat.yml
RUN chmod 0644 /etc/filebeat/filebeat.yml

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY config/supervisor/7.2/supervisor.prod.conf /etc/supervisor/conf.d/supervisord.conf

COPY config/php/php.ini /etc/php7/conf.d/50-setting.ini
COPY config/php/opcache.ini /etc/php7/cli/conf.d/opcache.ini
COPY config/php/opcache.ini /etc/php7/fpm/conf.d/opcache.ini
COPY config/php/php-fpm.conf /etc/php7/php-fpm.conf

WORKDIR /app