FROM jjpastor3/docker-ubuntu:7.2

ENV NOTVISIBLE="in users profile"

# Install base packages
RUN apt-get update && apt-get install -y --allow-unauthenticated \
      openssh-server \
      git \
      ant \
      php7.2-xdebug \
      nano \
      vim \
      openjdk-8-jdk \
      host \
      inetutils-ping \
    && rm -rf /var/lib/apt/lists/* \
    && composer global require "hirak/prestissimo:^0.3" \
    && composer global config minimum-stability dev \
    && composer global config prefer-stable true \
    && mkdir -p /var/run/sshd \
    && echo "root:randockdev" | chpasswd \
    && sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd \
    && echo "export VISIBLE=now" >> /etc/profile \
    && composer global require friendsofphp/php-cs-fixer:^3 \
    && composer global require edgedesign/phpqa --update-no-dev \
    && composer global require phpstan/phpstan --update-no-dev \
    && composer global require jakub-onderka/php-parallel-lint --update-no-dev \
    && composer global require jakub-onderka/php-console-highlighter --update-no-dev \
    && composer global update

# frontend things
RUN apt-get update && apt-get install -y ruby ruby-dev nodejs npm autoconf libtool && \
npm -g install uglify-js uglifycss && \
npm -g install less && \
gem update --system && \
gem install sass compass

# Install Zsh
RUN git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh \
    && cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc \
    && chsh -s /bin/zsh \
    && echo "TERM=xterm-256color" >> ~/.zshrc \
    && wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf \
    && wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf \
    && mkdir ~/.fonts/ \
    && mv PowerlineSymbols.otf ~/.fonts/ \
    && mkdir -p ~/.config/fontconfig/conf.d \
    && mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/ \
    && sed -i 's/robbyrussell/agnoster/g' ~/.zshrc \
    && echo 'source $HOME/.bash_aliases' >> ~/.zshrc

COPY config/supervisor/7.2/supervisor.conf /etc/supervisor/conf.d/supervisord.conf
COPY config/php/php.ini /etc/php/7.2/cli/conf.d/php.ini
COPY config/php/xdebug.ini /etc/php/7.2/cli/conf.d/20-xdebug.ini

COPY config/php/aliases /root/.bash_aliases

COPY config/ssh-fpm.pub /config/ssh-fpm.pub

RUN mkdir -p ~/.ssh \
    && cat /config/ssh-fpm.pub >> ~/.ssh/authorized_keys

COPY config/keys/randock.common-bundle /root/.ssh/github_common
COPY config/keys/randock.metronic-bundle /root/.ssh/github_metronic
COPY config/keys/randock.canvas-bundle /root/.ssh/github_canvas
COPY config/keys/randock.test-bundle /root/.ssh/github_testbundle
COPY config/keys/randock.github_randock_visa_account_api /root/.ssh/github_randock_visa_account_api
COPY config/keys/randock.tentered-bundle /root/.ssh/github_tentered
COPY config/keys/randock.dvp_api /root/.ssh/github_randock_dvp_api

COPY config/ssh-config /root/.ssh/config

RUN ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN chmod 0600 /root/.ssh/github_common
RUN chmod 0600 /root/.ssh/github_metronic
RUN chmod 0600 /root/.ssh/github_canvas
RUN chmod 0600 /root/.ssh/github_testbundle
RUN chmod 0600 /root/.ssh/github_randock_visa_account_api
RUN chmod 0600 /root/.ssh/github_tentered
RUN chmod 0600 /root/.ssh/github_randock_dvp_api

ENV PATH="/root/.composer/vendor/bin:${PATH}"

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/conf.d/supervisord.conf"]

EXPOSE 22 9000 80

WORKDIR /app